export const datacd = [
    {
      id: '001',
      picture: '/img/4runner.png',
      name: 'TOYOTA 4RUNNER',
      price: '$4900',
    },
    {
      id: '002',
      picture: '/img/70cup.png',
      name: 'HONDA 70 CUP',
      price: '$650',
    },
    {
      id: '003',
      picture: '/img/ae86.png',
      name: 'TOYOTA AE 86 TRUENO',
      price: '$4300',
    },
    {
      id: '004',
      picture: '/img/aerox.png',
      name: 'YAMAHA AEROX 155',
      price: '$1900',
    },
    {
      id: '005',
      picture: '/img/alpinab.png',
      name: 'BMW 750 LI ALPINAB',
      price: '$2900',
    },
    {
      id: '006',
      picture: '/img/artisan.png',
      name: 'LEXUS LM350 ARTISAN',
      price: '$4600',
    },
    {
      id: '007',
      picture: '/img/aventador.png',
      name: 'LAMBORGHINI AVENTADOR LP700',
      price: '$8100',
    },
    {
      id: '008',
      picture: '/img/bean.png',
      name: 'MINI COOPER MR BEAN',
      price: '$1000',
    },
    {
      id: '009',
      picture: '/img/bentley.png',
      name: 'BENTLEY BENTAYGA',
      price: '$5800',
    },
    {
      id: '010',
      picture: '/img/benz.png',
      name: 'MERCEDES BENZ 190E',
      price: '$4100',
    },
    {
      id: '011',
      picture: '/img/c63.png',
      name: 'MERCEDES BENZ C63 AMG',
      price: '$4200',
    },
    {
      id: '012',
      picture: '/img/cadillac.png',
      name: 'CADILLAC',
      price: '$4200',
    },
    {
      id: '013',
      picture: '/img/camaro.png',
      name: 'CHEVROLET CAMARO SS69',
      price: '$2100',
    },
    {
      id: '014',
      picture: '/img/camry.png',
      name: 'TOYOTA CAMRY',
      price: '$3300',
    },
    {
      id: '015',
      picture: '/img/cayenne.png',
      name: 'PORSCHE CAYENNE',
      price: '$6300',
    },
    {
      id: '016',
      picture: '/img/cbr.png',
      name: 'HONDA CBR 250 RR',
      price: '$2900',
    },
    {
      id: '017',
      picture: '/img/cbr650.png',
      name: 'HONDA CBR 650 R',
      price: '$4700',
    },
    {
      id: '018',
      picture: '/img/convertible.png',
      name: 'MINI COOPER CONVERTIBLE',
      price: '$5900',
    },
    {
      id: '019',
      picture: '/img/corolla.png',
      name: 'TOYOTA COROLLA HATCHBACK',
      price: '$3800',
    },
    {
      id: '020',
      picture: '/img/cruiser.png',
      name: 'TOYOTA LAND CRUISER 30TH ANNIVERSARRY',
      price: '$2990',
    },
    {
      id: '021',
      picture: '/img/cruiser200.png',
      name: 'TOYOTA LAND CRUISER 200',
      price: '$2400',
    },
    {
      id: '022',
      picture: '/img/crv.png',
      name: 'HONDA CRV 2019',
      price: '$1600',
    },
    {
      id: '023',
      picture: '/img/defender.png',
      name: 'LAND ROVER DEFENDER 110',
      price: '$6300',
    },
    {
      id: '024',
      picture: '/img/ducati900.png',
      name: 'DUCATI 900 CAFERACER',
      price: '$2750',
    },
    {
      id: '025',
      picture: '/img/e30.png',
      name: 'BMW M3 E30',
      price: '$2900',
    },
    {
      id: '026',
      picture: '/img/e36.png',
      name: 'BMW M3 E36',
      price: '$3600',
    },
    {
      id: '027',
      picture: '/img/e39.png',
      name: 'BMW M5 E39',
      price: '$2800',
    },
    {
      id: '028',
      picture: '/img/e55.png',
      name: 'MERCEDES BENZ E55',
      price: '$2100',
    },
    {
      id: '029',
      picture: '/img/e63s.png',
      name: 'MERCEDES BENZ E63S WAGON',
      price: '$5900',
    },
    {
      id: '030',
      picture: '/img/evo6.png',
      name: 'MITSUBISHI EVO 6',
      price: '$5300',
    },
    {
      id: '031',
      picture: '/img/f80.png',
      name: 'BMW M5 F80',
      price: '$4100',
    },
    {
      id: '032',
      picture: '/img/fj40.png',
      name: 'TOYOTA LAND CRUISER FJ40',
      price: '$1800',
    },
    {
      id: '033',
      picture: '/img/ford.png',
      name: 'FORD FIESTA WRC',
      price: '$3800',
    },
    {
      id: '034',
      picture: '/img/fortuner.png',
      name: 'TOYOTA FORTUNER',
      price: '$2800',
    },
    {
      id: '035',
      picture: '/img/goldwing.png',
      name: 'HONDA GOLDWING 2018',
      price: '$1900',
    },
    {
      id: '036',
      picture: '/img/golf.png',
      name: 'VW GOLF MK7',
      price: '$3900',
    },
    {
      id: '037',
      picture: '/img/gtr35.png',
      name: 'NISSAN GTR R35',
      price: '$7900',
    },
    {
      id: '038',
      picture: '/img/harley.png',
      name: 'FOX HARLEY',
      price: '$300',
    },
    {
      id: '039',
      picture: '/img/iron.png',
      name: 'HARLEY IRON 883',
      price: '$3800',
    },
    {
      id: '040',
      picture: '/img/jeep.png',
      name: 'JEEP DWRANGLER',
      price: '$2900',
    },
    {
      id: '041',
      picture: '/img/klx.png',
      name: 'KAWASAKI KLX 150',
      price: '$1200',
    },
    {
      id: '042',
      picture: '/img/knucklehead.png',
      name: 'HARLEY KNUCKLEHEAD',
      price: '$2900',
    },
    {
      id: '043',
      picture: '/img/m3f.png',
      name: 'BMW M3 F80',
      price: '$3300',
    },
    {
      id: '044',
      picture: '/img/mansory.png',
      name: 'AUDI RS7 MANSORY',
      price: '$6900',
    },
    {
      id: '045',
      picture: '/img/miata.png',
      name: 'MAZDA MX5 MIATA OLD',
      price: '$5200',
    },
    {
      id: '046',
      picture: '/img/ninja.png',
      name: 'KAWASAKI NINJA R150',
      price: '$800',
    },
    {
      id: '047',
      picture: '/img/pajero.png',
      name: 'MITSUBISHI PAJERO',
      price: '$2800',
    },
    {
      id: '048',
      picture: '/img/panamera.png',
      name: 'PORSCHE PANAMERA',
      price: '$6600',
    },
    {
      id: '049',
      picture: '/img/q8.png',
      name: 'AUDI RS Q8',
      price: '$4200',
    },
    {
      id: '050',
      picture: '/img/r8.png',
      name: 'AUDI R8 BODYKIT',
      price: '$6800',
    },
    {
      id: '051',
      picture: '/img/redeye.png',
      name: 'DODGE CHALLANGER REDEYE',
      price: '$5100',
    },
    {
      id: '052',
      picture: '/img/roadking.png',
      name: 'HARLEY SHABU ROADKING',
      price: '$4000',
    },
    {
      id: '053',
      picture: '/img/rover.png',
      name: 'RANGE ROVER STECH',
      price: '$2800',
    },
    {
      id: '054',
      picture: '/img/rubicon.png',
      name: 'JEEP GLADIATOR RUBICON',
      price: '$7500',
    },
    {
      id: '055',
      picture: '/img/s63.png',
      name: 'MERCEDES BENZ S63 MANSORY',
      price: '$4200',
    },
    {
      id: '056',
      picture: '/img/s500.png',
      name: 'MERCEDES BENZ S500',
      price: '$4100',
    },
    {
      id: '057',
      picture: '/img/scoopy.png',
      name: 'HONDA SCOOPY',
      price: '$600',
    },
    {
      id: '058',
      picture: '/img/skyline32.png',
      name: 'NISSAN SKYLINE R32n',
      price: '$6200',
    },
    {
      id: '059',
      picture: '/img/sprint.png',
      name: 'VESPA SPRINT',
      price: '$1600',
    },
    {
      id: '060',
      picture: '/img/storm.png',
      name: 'JEEP STORM TROOPERHAWK',
      price: '$4100',
    },
    {
      id: '061',
      picture: '/img/tacoma.png',
      name: 'TOYOTA TACOMA',
      price: '$3900',
    },
    {
      id: '062',
      picture: '/img/taycan.png',
      name: 'PORSCHE TAYCAN',
      price: '$5300',
    },
    {
      id: '063',
      picture: '/img/titan.png',
      name: 'NISSAN TITAN ',
      price: '$7200',
    },
    {
      id: '064',
      picture: '/img/tmax.png',
      name: 'YAMAHA T-MAX 560',
      price: '$1800',
    },
    {
      id: '065',
      picture: '/img/urus.png',
      name: 'LAMBORGHINI URUS',
      price: '$6900',
    },
    {
      id: '066',
      picture: '/img/wagon.png',
      name: 'BMW M5 WAGON',
      price: '$4900',
    },
    {
      id: '067',
      picture: '/img/x7.png',
      name: 'BMW X7',
      price: '$5800',
    },
    {
      id: '068',
      picture: '/img/x6.png',
      name: 'BMW X6',
      price: '$3900',
    },
    {
      id: '069',
      picture: '/img/yzf.png',
      name: 'YAMAHA YZF R6',
      price: '$3900',
    },
    {
      id: '070',
      picture: '/img/z1000.png',
      name: 'KAWASAKI Z1000',
      price: '$4000',
    },
    {
      id: '071',
      picture: '/img/zx6r.png',
      name: 'KAWASAKI ZX6R',
      price: '$3800',
    },
    {
      id: '072',
      picture: '/img/zx14r.png',
      name: 'KAWASAKI ZX14R',
      price: '$3900',
    },
    {
        id: '073',
        picture: '/img/cb500.png',
        name: 'HONDA CB 500X',
        price: '$2900',
      },
      {
        id: '074',
        picture: '/img/cb100.png',
        name: 'HONDA CB 100',
        price: '$1200',
      },
  ]