export const datas = [
    {
      id: '002',
      picture: '/img/70cup.png',
      name: 'HONDA 70 CUP',
      price: '$650',
    },
    {
      id: '004',
      picture: '/img/aerox.png',
      name: 'YAMAHA AEROX 155',
      price: '$1900',
    },
    {
      id: '016',
      picture: '/img/cbr.png',
      name: 'HONDA CBR 250 RR',
      price: '$2900',
    },
    {
      id: '017',
      picture: '/img/cbr650.png',
      name: 'HONDA CBR 650 R',
      price: '$4700',
    },
    {
      id: '024',
      picture: '/img/ducati900.png',
      name: 'DUCATI 900 CAFERACER',
      price: '$2750',
    },
    {
      id: '035',
      picture: '/img/goldwing.png',
      name: 'HONDA GOLDWING 2018',
      price: '$1900',
    },
    {
      id: '038',
      picture: '/img/harley.png',
      name: 'FOX HARLEY',
      price: '$2800',
    },
    {
      id: '039',
      picture: '/img/iron.png',
      name: 'HARLEY IRON 883',
      price: '$3800',
    },
    {
      id: '041',
      picture: '/img/klx.png',
      name: 'KAWASAKI KLX 150',
      price: '$1200',
    },
    {
      id: '042',
      picture: '/img/knucklehead.png',
      name: 'HARLEY KNUCKLEHEAD',
      price: '$2900',
    },
    {
      id: '046',
      picture: '/img/ninja.png',
      name: 'KAWASAKI NINJA R150',
      price: '$800',
    },
    {
      id: '052',
      picture: '/img/roadking.png',
      name: 'HARLEY SHABU ROADKING',
      price: '$4000',
    },
    {
      id: '057',
      picture: '/img/scoopy.png',
      name: 'HONDA SCOOPY',
      price: '$600',
    },
    {
      id: '059',
      picture: '/img/sprint.png',
      name: 'VESPA SPRINT',
      price: '$1600',
    },
    {
      id: '064',
      picture: '/img/tmax.png',
      name: 'YAMAHA T-MAX 560',
      price: '$1800',
    },
    {
      id: '069',
      picture: '/img/yzf.png',
      name: 'YAMAHA YZF R6',
      price: '$3900',
    },
    {
      id: '070',
      picture: '/img/z1000.png',
      name: 'KAWASAKI Z1000',
      price: '$4000',
    },
    {
      id: '071',
      picture: '/img/zx6r.png',
      name: 'KAWASAKI ZX6R',
      price: '$3800',
    },
    {
      id: '072',
      picture: '/img/zx14r.png',
      name: 'KAWASAKI ZX14R',
      price: '$3900',
    },
    {
        id: '073',
        picture: '/img/cb500.png',
        name: 'HONDA CB 500X',
        price: '$2900',
      },
      {
        id: '074',
        picture: '/img/cb100.png',
        name: 'HONDA CB 100',
        price: '$1200',
      },
    ]